### ISSUE TITLE
 what is "train_images_idx.txt" for ImageNet?

### ISSUE THREAD

**Issue by he-y** [Fangyh09/Image2LMDB#1]
what is "train_images_idx.txt" for ImageNet?

**Comment by Fangyh09** [comment]
@he-y 
This is an output file for demo. You can comment it.

https://github.com/Fangyh09/Image2LMDB/blob/23c4c2bb431c1996ee3efa5ae2cde2a4493244cd/folder2lmdb.py#L161-L164

**Comment by Fangyh09** [comment]
I am sorry for the confusion. 
I have updated the readme.
