### ISSUE TITLE
Training speed

### ISSUE THREAD

**Issue by hkunzhe** [Fangyh09/Image2LMDB#6]
Hi, thanks for this script!
Will converting the ImageFolder to the LMDB file make training faster?

**Comment by buzhangjiuzhou** [comment]
It depends on your bottleneck of training.
In my case, the cloud I using was based on NFS file system, which is surprisingly slow when loading large amount of small files. So it  do faster 1.5 fold than before(Without it I train 2K steps per hour, and now 3K.).
